Pokemon/Pokedex/urls.py
from django.urls import path
from . import views

app_name = 'Pokedex'



urlpatterns = [
path('', views.home_page, name='home_page'),
path('create/', views.form_page, name='form_page')

]

Pokemon/Pokemon/urls.py
from django.contrib import admin
from django.urls import path,include
from Pokedex import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Pokedex.urls')),
]

Pokemon/Pokedex/models.py
from django.db import models

# Create your models here.
diff_types = (
	('Normal','NORMAL'),
	('Fire','FIRE'),
	('Water','WATER'),
	('Grass','GRASS'),
	('Psychic','PSYCHIC'),
	('Fighting','FIGHTING'),
	('Lightning','LIGHTNING'),
	)


class Pokemon(models.Model):

	name = models.CharField(max_length=168)
	the_type = models.CharField(max_length=168, choices = diff_types, default='normal')
	hp = models.IntegerField()

Pokemon/Pokedex/forms.py
from django.forms import ModelForm
from .models import Pokemon

class EnterPokemon(ModelForm):
	class Meta:
		model = Pokemon
		fields = '__all__'

Pokemon/Pokedex/views.py
from django.shortcuts import render
from .models import Pokemon
from .forms import EnterPokemon
# Create your views here.
def home_page(request):
	entry_dict = {'pokemon_records': Pokemon.objects.order_by('the_type')}
	return render(request, 'Pokedex/homepage.html', context=entry_dict)

def form_page(request):
	form = EnterPokemon()

	if request.method == "POST":
		form = EnterPokemon(request.POST)

		if form.is_valid():
			form.save(commit=True)
			return home_page(request)
		else:
			print("Not a real pokemon!")
	return render(request, 'Pokedex/newpokemon.html', {'form':form})

Pokemon/Pokedex/templates/Pokedex/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/design.css' %}">
	<title></title>
</head>
<body id="bground">

	  <nav class="navbar navbar-light navbar-static-top" style="background-color: #ff4d4d;">
  			<a class="navbar-brand" href="{% url 'Pokedex:home_page' %}">
    		<img src='{% static "images/charizard.png" %}' width="30" height="30" class="d-inline-block align-top" alt="">Pokedex</a>
    		<a class= "navbar-link" href="#">Home</a>
    		<a class= "navbar-lin" href="#">Types</a>
	  </nav>

	<div class="container">
	  	
	</div>
	  {% block body_block %}

	  {% endblock %}
	

</body>
</html>

Pokemon/Pokedex/templates/Pokedex/homepage.html
<!DOCTYPE html>
{% extends "Pokedex/base.html" %}



	{% block body_block %}	
	<h2 id="welcome">Welcome to the Pokedex!</h2>
	<a href="{% url 'Pokedex:form_page' %}"><button type="button" class="btn btn-danger">Add Pokemon</button></a>
	<div class="container">	
	<table class="table table-dark">
	  <thead>
	    <tr>
	      <th scope="col">Pokemon</th>	
	      <th scope="col">Type</th>	
	      <th scope="col">Hit Points</th>	
	    </tr>
	  </thead>
	  {% for pokemon in pokemon_records %}
	  <tbody>
		<tr>
		  <td>{{ pokemon.name }}</td>
		  <td>{{ pokemon.the_type }}</td>
		  <td>{{ pokemon.hp }}</td>
		</tr>
	  </tbody>
	  {% endfor %}
	</table>
	</div>
	{% endblock %}

Pokemon/Pokedex/templates/Pokedex/newpokemon.html
<!DOCTYPE html>
{% extends "Pokedex/base.html" %}

	{% block body_block %}
	<title>Add Pokemon</title>
	<div class="container">
 	<div class="jumbotron">
	<h1>Please add a pokemon to the Pokedex</h1>
	<form method="POST">
		{{form.as_p}}
		{% csrf_token %}
		<input type="submit" value="Add Pokemon">
	</form>
	</div>
	</div>
	{% endblock %}